[package]
name = "substratee-client"
version = "4.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[dependencies]
substrate-api-client = { tag = "api-M1.5", git = "https://github.com/scs/substrate-api-client.git"}
log = "0.4"
env_logger = "0.7"
hex = "0.4"
json = "0.12.0"
substrate-bip39 = "0.3.1"
tiny-bip39 = "0.6.2"
serde_json      = { version = "1.0"}
clap            = { version = "2.33", features = [ "yaml" ] }
primitive-types = { version = "0.6.1", default-features = false, features = ["codec"] }
base58 			        = "0.1"
chrono = "*"

[dependencies.serde]
features = ["derive"]
optional = true
version = "1.0"

[dependencies.codec]
default-features = false
package = "parity-scale-codec"
features = ["derive"]
version = "1.0.0"

[dependencies.primitives]
git = 'https://github.com/paritytech/substrate'
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "substrate-primitives"

[dependencies.sr-primitives]
git = "https://github.com/paritytech/substrate"
package = "sr-primitives"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.keystore]
git = 'https://github.com/paritytech/substrate'
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "substrate-keystore"

[dependencies.balances]
git = 'https://github.com/paritytech/substrate'
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "pallet-balances"
default-features=false

[dependencies.system]
git = 'https://github.com/paritytech/substrate'
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "palette-system"
default-features=false

[dependencies.substratee_node_runtime]
git = "https://github.com/scs/substraTEE-node"
rev = "7328b37166fdffcc74cf11763084d67029945df9"
package = "substratee-node-runtime"

[dependencies.keyring]
git = 'https://github.com/paritytech/substrate'
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "substrate-keyring"

[dependencies.app-crypto]
git = "https://github.com/paritytech/substrate"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "substrate-application-crypto"

#[patch.crates-io]
#ed25519-dalek = { git = "https://github.com/scs/ed25519-dalek.git", branch = "no_std_sgx"}