[package]
name = "substratee_client"
version = "4.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.7.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
substrate-bip39 = "0.3.1"
chrono = "*"
base58 = "0.1"

clap            = { version = "2.33", features = [ "yaml" ] }
blake2-rfc      = { version = "0.2.18", default-features = false}
codec           = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
primitive-types = { version = "0.6", default-features = false, features = ["codec"] }

sgx_types           = { rev = "v1.1.0",git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_crypto_helper   = { rev = "v1.1.0",git = "https://github.com/apache/teaclave-sgx-sdk.git", default-features = false }

[dependencies.my_node_runtime]
git = "https://github.com/scs/substraTEE-node"
#rev = "c2309a2f6b140ad914ea809a0348c9432c6c7d30"
branch = "brenzi-sharding"
package = "substratee-node-runtime"

[dependencies.substrate-api-client]
git = "https://github.com/scs/substrate-api-client"
tag = "api-M1.5"

[dependencies.substratee-node-calls]
path = "../substratee-node-calls"

[dependencies.substratee_worker_api]
path = "../worker/worker-api"

[dependencies.system]
git = "https://github.com/paritytech/substrate"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "palette-system"

[dependencies.primitives]
git = "https://github.com/paritytech/substrate"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "substrate-primitives"
features = ["full_crypto"]

[dependencies.node-primitives]
git = "https://github.com/paritytech/substrate"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.keyring]
git = "https://github.com/paritytech/substrate"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "substrate-keyring"

[dependencies.runtime_primitives]
git = "https://github.com/paritytech/substrate"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "sr-primitives"
#default-features = false

[dependencies.indices]
git = "https://github.com/paritytech/substrate"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "pallet-indices"

[dependencies.substratee-stf]
path = "../stf"
default-features = false
