[package]
name = "substratee_client"
version = "4.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[dependencies]
ws = "0.7"
hex = "0.3"
log = "0.4"
rand = "0.6"
env_logger = "0.6"
schnorrkel = { version = "0.8.4", features = ["preaudit_deprecated"] }
serde = "1.0"
serde_json = "1.0"
tiny-bip39 = "0.6.0"
hex-literal = "0.2.0"
serde_derive = "1.0"
substrate-bip39 = "0.2.2"

clap            = { version = "2.33", features = [ "yaml" ] }
blake2-rfc      = { version = "0.2.18", default-features = false}
codec           = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
primitive-types = { version = "0.5.0", default-features = false, features = ["codec"] }

sgx_types           = { rev = "v1.0.9",git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_crypto_helper   = { rev = "v1.0.9",git = "https://github.com/baidu/rust-sgx-sdk", default-features = false }

[dependencies.my_node_runtime]
git = "https://github.com/scs/substraTEE-node"
tag = "M5"
package = "substratee-node-runtime"
features = ["no_global_allocator"]

[dependencies.substrate-api-client]
git = "https://github.com/scs/substrate-api-client"
tag = "api-M1.3"

[dependencies.substratee-node-calls]
path = "../substratee-node-calls"

[dependencies.substratee_worker_api]
path = "../worker/worker-api"

[dependencies.system]
git = "https://github.com/paritytech/substrate"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"
package = "srml-system"

[dependencies.primitives]
git = "https://github.com/paritytech/substrate"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"
package = "substrate-primitives"

[dependencies.node-primitives]
git = "https://github.com/paritytech/substrate"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.substrate-keyring]
git = "https://github.com/paritytech/substrate"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.runtime_primitives]
git = "https://github.com/paritytech/substrate"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"
package = "sr-primitives"
default-features = false

[dependencies.indices]
git = 'https://github.com/paritytech/substrate'
rev = '9b08e7ff938a45dbec7fcdb854063202e2b0cb48'
package = "srml-indices"

[dependencies.substratee-stf]
path = "../stf"
default-features = false
