[package]
name = "its-storage"
version = "0.8.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2018"

[dependencies]
# crate.io
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
log = "0.4"
parking_lot = "0.11.1"
rocksdb = "0.17.0"
thiserror = "1.0"

# local
its-primitives = { path = "../primitives" }

# Substrate dependencies
sp-core = { version = "6.0.0", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19" }

[dev-dependencies]
# crate.io
mockall = { version = "0.10.1" }
temp-dir = "0.1"
# local
itp-types = { path = "../../core-primitives/types" }
its-test = { path = "../test" }
itp-time-utils = { path = "../../core-primitives/time-utils", default-features = false }

[features]
mocks = []
