[package]
name = "its-storage"
version = "0.8.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2018"

[dependencies]
# crate.io
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
log = "0.4"
parking_lot = "0.12.1"
rocksdb = "0.17.0"
thiserror = "1.0"

# integritee
itp-types = { git = "https://github.com/integritee-network/pallets.git", branch = "sdk-v0.9.0-polkadot-v0.9.26" }
sidechain-primitives = { git = "https://github.com/integritee-network/pallets.git", branch = "sdk-v0.9.0-polkadot-v0.9.26" }

# Substrate dependencies
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.26" }

[dev-dependencies]
# crate.io
mockall = "0.11"
temp-dir = "0.1"
# local
sidechain-test = { git = "https://github.com/integritee-network/pallets.git", branch = "sdk-v0.9.0-polkadot-v0.9.26" }
itp-time-utils = { path = "../../core-primitives/time-utils" }

[features]
mocks = []
