[package]
name = "itc-parentchain-indirect-calls-executor"
version = "0.8.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2018"
resolver = "2"

[dependencies]
# sgx dependencies
sgx_types = { branch = "v1.1.4-testing", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = { branch = "v1.1.4-testing", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

# local dependencies
ita-stf = { path = "../../../app-libs/stf", default-features = false }
itp-extrinsics-factory = { path = "../../../core-primitives/extrinsics-factory", default-features = false }
itp-ocall-api = { path = "../../../core-primitives/ocall-api", default-features = false }
itp-settings = { path = "../../../core-primitives/settings" }
itp-sgx-crypto = { path = "../../../core-primitives/sgx/crypto", default-features = false }
itp-stf-executor = { path = "../../../core-primitives/stf-executor", default-features = false }
itp-types = { path = "../../../core-primitives/types", default-features = false }

# sgx enabled external libraries
rust-base58_sgx = { package = "rust-base58", rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/rust-base58-sgx", optional = true, default-features = false, features = ["mesalock_sgx"] }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# std compatible external libraries (make sure these versions match with the sgx-enabled ones above)
thiserror = { version = "1.0", optional = true }
rust-base58 = { package = "rust-base58", version = "0.0.4", optional = true }

# no-std compatible libraries
codec  = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4", default-features = false }
sp-core = { version = "4.0.0-dev", default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-runtime = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master"}

# scs/integritee
substrate-api-client = { git = "https://github.com/scs/substrate-api-client", branch = "master", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "ita-stf/std",
    "itp-extrinsics-factory/std",
    "itp-ocall-api/std",
    "itp-sgx-crypto/std",
    "itp-stf-executor/std",
    "itp-types/std",
    "log/std",
    "rust-base58",
    "sp-core/std",
    "sp-runtime/std",
    "substrate-api-client/std",
    "thiserror",
]
sgx = [
    "sgx_tstd",
    "ita-stf/sgx",
    "itp-extrinsics-factory/sgx",
    "itp-sgx-crypto/sgx",
    "itp-stf-executor/sgx",
    "itp-types/sgx",
    "rust-base58_sgx",
    "thiserror_sgx",
]
