[package]
name = "itp-storage"
version = "0.9.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["chain-error"] }
derive_more = { version = "0.99.5" }
frame-metadata = { version = "15.0.0", features = ["v14"], default-features = false }
hash-db = { version = "0.15.2", default-features = false }
thiserror = { version = "1.0.26", optional = true }

# sgx deps
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
thiserror-sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# substrate deps
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-core = { default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-trie = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

# integritee
itp-types = { default-features = false, path = "../types" }

[dev-dependencies]
sp-state-machine = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-metadata/std",
    "frame-support/std",
    "hash-db/std",
    "itp-types/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-trie/std",
    "thiserror",
]
sgx = [
    "sgx_tstd",
    "thiserror-sgx",
]
test = []
