[package]
name = "itp-storage"
version = "0.8.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2018"
resolver = "2"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["chain-error"] }
derive_more = { version = "0.99.5" }
hash-db = { version = "0.15.2", default-features = false }
thiserror = { version = "1.0.26", optional = true }

# sgx deps
thiserror-sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

# substrate deps
frame-metadata = { version = "14.0.0", features = ["v13"], default-features = false, git = "https://github.com/paritytech/frame-metadata.git", branch = "main" }
frame-support = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master"}
sp-core = { version = "5.0.0", default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "master"}
sp-runtime = { version = "5.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master"}
sp-std = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master"}
sp-trie = { version = "5.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master"}

[dev-dependencies]
sp-state-machine = { version = "0.11.0", git = "https://github.com/paritytech/substrate.git", branch = "master"}

[features]
default = ["std"]
std = [
    "codec/std",
    "hash-db/std",
    "frame-metadata/std",
    "frame-support/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-trie/std",
    "thiserror",
]
sgx = [
    "sgx_tstd",
    "thiserror-sgx"
]
test = []
