[package]
name = "substratee-sidechain-primitives"
version = "0.8.0"
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive", "full"] }
serde = { version = "1.0", optional = true, features = ["derive"]}

# substrate deps
sp-core = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master"}
sp-std = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master"}
sp-runtime = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master"}

[features]
default = ["std"]
std = [
    "codec/std",
    "serde",
    "sp-core/std",
    "sp-std/std",
    "sp-runtime/std",
]