[package]
name = "itc-parentchain-light-client"
version = "0.9.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "chain-error"] }
derive_more = { version = "0.99.5" }
finality-grandpa = { version = "0.16.0", default-features = false, features = ["derive-codec"] }
hash-db = { version = "0.15.2", default-features = false }
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
log = { version = "0.4", default-features = false }
num = { package = "num-traits", version = "0.2", default-features = false }
thiserror = { version = "1.0.26", optional = true }

# sgx-deps
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["untrusted_fs"], optional = true }
sgx_types = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
thiserror-sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# local deps
itp-ocall-api = { path = "../../../core-primitives/ocall-api", default-features = false }
itp-sgx-io = { path = "../../../core-primitives/sgx/io", default-features = false }
itp-storage = { path = "../../../core-primitives/storage", default-features = false }
itp-types = { path = "../../../core-primitives/types", default-features = false }

# substrate deps
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-application-crypto = { default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-core = { default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-finality-grandpa = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-trie = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }

# test & mock dependencies
itc-parentchain-test = { optional = true, default-features = false, path = "../../../core/parentchain/test" }
# We can't really make this optional due to feature flag complexities.
itp-sgx-temp-dir = { version = "0.1", default-features = false, path = "../../../core-primitives/sgx/temp-dir" }
itp-test = { optional = true, default-features = false, features = ["sgx"], path = "../../../core-primitives/test" }

[dev-dependencies]
itc-parentchain-test = { path = "../../../core/parentchain/test" }
itp-test = { path = "../../../core-primitives/test" }
itp-sgx-temp-dir = { version = "0.1", path = "../../../core-primitives/sgx/temp-dir" }

[features]
default = ["std"]
std = [
    "codec/std",
    "hash-db/std",
    "num/std",
    "log/std",
    "finality-grandpa/std",
    "thiserror",

    # substrate deps
    "frame-system/std",
    "sp-core/std",
    "sp-application-crypto/std",
    "sp-finality-grandpa/std",
    "sp-runtime/std",
    "sp-trie/std",

    # local deps
    "itp-ocall-api/std",
    "itp-storage/std",
    "itp-sgx-io/std",
    "itp-types/std",

    # mock deps
    "itp-sgx-temp-dir/std",
]
sgx = [
    "sgx_tstd",
    "thiserror-sgx",
    "itp-sgx-io/sgx",
    "itp-storage/sgx",
    "itp-sgx-temp-dir/sgx",
]
mocks = [
    "itc-parentchain-test",
]

test = ["mocks", "itp-test"]
