[package]
name = "itp-test"
version = "0.8.0"
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
derive_more = { version = "0.99.5" }

# sgx deps
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

# substrate deps
sp-core = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master"}
sp-runtime = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master"}
sp-std = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master"}

# local deps
itp-teerex-storage = { path = "../pallet-teerex-storage", default-features = false }
itp-teerex = { path = "../node", default-features = false }
itp-ocall-api = { path = "../ocall-api", default-features = false }
itp-storage-verifier = { path = "../get-storage-verified", default-features = false }
itp-storage = { path = "../storage", default-features = false, features = ["test"] }
itp-core = { path = "../worker", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    "itp-storage/std",
    "itp-teerex-storage/std",
    "itp-teerex/std",
    "itp-ocall-api/std",
    "itp-storage-verifier/std",
    "itp-core/std",
]
sgx = ["sgx_tstd"]