[package]
name = "itp-top-pool"
version = "0.9.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"

[dependencies]
# sgx dependencies
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true, features = ["net", "thread", "untrusted_time"] }
sgx_types = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

# local dependencies
ita-stf = { path = "../../app-libs/stf", default-features = false }
itc-direct-rpc-server = { path = "../../core/direct-rpc-server", default-features = false }
itp-stf-primitives = { path = "../stf-primitives", default-features = false }
itp-types = { path = "../types", default-features = false }
its-primitives = { path = "../../sidechain/primitives", default-features = false }

# sgx enabled external libraries
jsonrpc-core_sgx = { package = "jsonrpc-core", git = "https://github.com/scs/jsonrpc", branch = "no_std_v18", default-features = false, optional = true }
linked-hash-map_sgx = { package = "linked-hash-map", git = "https://github.com/mesalock-linux/linked-hash-map-sgx", optional = true }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# std compatible external libraries (make sure these versions match with the sgx-enabled ones above)
jsonrpc-core = { version = "18", optional = true }
linked-hash-map = { version = "0.5.2", optional = true }
thiserror = { version = "1.0", optional = true }

# no-std compatible libraries
byteorder = { version = "1.4.2", default-features = false }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
derive_more = { version = "0.99.5" }
log = { version = "0.4", default-features = false }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
sp-application-crypto = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-core = { default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

# dev dependencies (for tests)
[dev-dependencies]
parity-util-mem = { version = "0.12.0", default-features = false, features = ["primitive-types"] }

[features]
default = ["std"]
sgx = [
    "sgx_tstd",
    "sgx_types",
    "ita-stf/sgx",
    "itc-direct-rpc-server/sgx",
    "jsonrpc-core_sgx",
    "linked-hash-map_sgx",
    "thiserror_sgx",
]
std = [
    "ita-stf/std",
    "itc-direct-rpc-server/std",
    "itp-types/std",
    "its-primitives/std",
    "jsonrpc-core",
    "linked-hash-map",
    "log/std",
    "serde/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-application-crypto/std",
    "thiserror",
]
mocks = []
