[package]
name = "itp-node-api-extensions"
version = "0.8.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2018"

[dependencies]
# crates.io
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
thiserror = { version = "1.0", optional = true }

# sgx dependencies
sgx_types = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

# sgx-compatible crates
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# substrate
sp-core = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.24" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.24" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.24" }

# scs
substrate-api-client = { git = "https://github.com/scs/substrate-api-client", default-features = false, branch = "polkadot-v0.9.24" }

# integritee
itp-types = { git = "https://github.com/integritee-network/pallets.git", branch = "master" }

[features]
default = ["std"]
std = [
    "substrate-api-client/std",
    "thiserror",
]
sgx = [
    "sgx_tstd",
    "thiserror_sgx",
]
# used for unit testing only!
mocks = []
