[package]
name = "sr-io"
version = "2.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.6", default-features = false }
hash-db = { version = "0.15.2", default-features = false }
libsecp256k1 = { version = "0.3.0", optional = true }
log = { version = "0.4.8", optional = true }

environmental = { version = "1.0.1", default-features = false, optional = true }
sgx_tstd      = { rev = "v1.1.0", git = "https://github.com/baidu/rust-sgx-sdk.git", features = ["untrusted_fs","net","backtrace"], optional = true}
sgx_types     = { rev = "v1.1.0", git = "https://github.com/baidu/rust-sgx-sdk.git", optional = true}
sgx_log       = { package = "log",  version = "0.4", git = "https://github.com/mesalock-linux/log-sgx", optional = true }
twox-hash =     { version = "1.3.0", default-features = false, optional = true }

[dependencies.rstd]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "sr-std"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.primitives]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "substrate-primitives"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.substrate-state-machine]
optional = true
git = "https://github.com/paritytech/substrate"
package = "substrate-state-machine"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.runtime-interface]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "substrate-runtime-interface"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.trie]
optional = true
git = "https://github.com/paritytech/substrate"
package = "substrate-trie"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.externalities]
optional = true
git = "https://github.com/paritytech/substrate"
package = "substrate-externalities"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.sgx-externalities]
path = "../externalities"

[features]
default = ["std"]
std = [
	"primitives/std",
	"codec/std",
	"rstd/std",
	"hash-db/std",
	"trie",
	"substrate-state-machine",
	"libsecp256k1",
	"runtime-interface/std",
	"externalities",
	"log",
]

sgx = [
	"sgx_tstd",
	"sgx_types",
	"sgx_log",
	"twox-hash",
	"environmental"
]

# These two features are used for `no_std` builds for the environments which already provides
# `#[panic_handler]`, `#[alloc_error_handler]` and `#[global_allocator]`.
#
# For the regular wasm runtime builds those are not used.
disable_panic_handler = []
disable_oom = []
disable_allocator = []
