[package]
name = "itp-node-api-factory"
version = "0.9.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"

[dependencies]
thiserror = { version = "1.0" }

# substrate
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

# local
itp-api-client-types = { path = "../api-client-types" }
