[package]
name = "its-state"
version = "0.9.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "chain-error"] }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
log = { version = "0.4", default-features = false }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }

# optional std deps
thiserror = { version = "1.0.9", optional = true }

# sgx deps
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

# sgx forks
thiserror_sgx = { package = "thiserror", version = "1.0.9", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# local deps
itp-sgx-externalities = { default-features = false, path = "../../core-primitives/substrate-sgx/externalities" }
itp-storage = { path = "../../core-primitives/storage", default-features = false }
its-primitives = { path = "../primitives", default-features = false }
sp-io = { optional = true, default-features = false, features = ["disable_oom", "disable_panic_handler", "disable_allocator"], path = "../../core-primitives/substrate-sgx/sp-io" }

# substrate deps
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

# test deps
[dev-dependencies]
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

[features]
default = ["std"]
std = [
    "log/std",
    "serde/std",
    # substrate
    "sp-std/std",
    "sp-core/std",
    # local crates
    "itp-sgx-externalities/std",
    "itp-storage/std",
    "its-primitives/std",
    "sp-io/std",
    # optional std crates
    "codec/std",
    "thiserror",
]
sgx = [
    # teaclave
    "sgx_tstd",
    # local crates
    "itp-sgx-externalities/sgx",
    "itp-storage/sgx",
    "sp-io/sgx",
    # sgx versions of std crates
    "thiserror_sgx",
]
