[package]
name = "itc-parentchain-block-importer"
version = "0.9.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"

[dependencies]
# sgx dependencies
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_types = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git" }

# local dependencies
ita-stf = { path = "../../../app-libs/stf", default-features = false }
itc-parentchain-indirect-calls-executor = { path = "../indirect-calls-executor", default-features = false }
itc-parentchain-light-client = { path = "../light-client", default-features = false }
itp-extrinsics-factory = { path = "../../../core-primitives/extrinsics-factory", default-features = false }
itp-settings = { path = "../../../core-primitives/settings" }
itp-stf-executor = { path = "../../../core-primitives/stf-executor", default-features = false }
itp-types = { path = "../../../core-primitives/types", default-features = false }

# sgx enabled external libraries
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# crates.io std-only compatible external libraries (make sure these versions match with the sgx-enabled ones above)
thiserror = { version = "1.0", optional = true }

# crates.io no-std compatible libraries
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4", default-features = false }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

[features]
default = ["std"]
std = [
    # local
    "ita-stf/std",
    "itc-parentchain-indirect-calls-executor/std",
    "itc-parentchain-light-client/std",
    "itp-extrinsics-factory/std",
    "itp-stf-executor/std",
    "itp-types/std",
    # no-std compatible libraries
    "codec/std",
    "log/std",
    "sp-runtime/std",
    # std compatible external
    "thiserror",
]
sgx = [
    # sgx
    "sgx_tstd",
    # local
    "ita-stf/sgx",
    "itc-parentchain-indirect-calls-executor/sgx",
    "itc-parentchain-light-client/sgx",
    "itp-extrinsics-factory/sgx",
    "itp-stf-executor/sgx",
    # sgx enabled external libraries
    "thiserror_sgx",
]

# feature to export mock implementations, only to be used for dev-dependencies!
mocks = []
