[package]
name = "its-top-pool-rpc-author"
version = "0.8.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = [
    "ita-stf/std",
    "itp-sgx-crypto/std",
    "itc-direct-rpc-server/std",
    "itc-tls-websocket-server/std",
    "itp-component-container/std",
    "itp-enclave-metrics/std",
    "itp-ocall-api/std",
    "itp-stf-state-handler/std",
    "itp-types/std",
    "its-top-pool/std",
    "jsonrpc-core",
    "log/std",
    "thiserror",
]
sgx = [
    "sgx_tstd",
    "sgx-crypto-helper",
    "jsonrpc-core_sgx",
    "ita-stf/sgx",
    "itc-direct-rpc-server/sgx",
    "itc-tls-websocket-server/sgx",
    "itp-component-container/sgx",
    "itp-enclave-metrics/sgx",
    "itp-sgx-crypto/sgx",
    "itp-stf-state-handler/sgx",
    "itp-types/sgx",
    "its-top-pool/sgx",
    "thiserror_sgx",
]
test = [ "itp-test/sgx" ]

[dependencies]
# sgx dependencies
sgx_types = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx-crypto-helper = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", package = "sgx_tcrypto_helper", optional = true }

# local dependencies
ita-stf = { path = "../../app-libs/stf", default-features = false }
itc-direct-rpc-server = { path = "../../core/direct-rpc-server", default-features = false }
itc-tls-websocket-server = { path = "../../core/tls-websocket-server", default-features = false }
itp-component-container = { path = "../../core-primitives/component-container", default-features = false }
itp-enclave-metrics = { path = "../../core-primitives/enclave-metrics", default-features = false }
itp-ocall-api = { path = "../../core-primitives/ocall-api", default-features = false }
itp-sgx-crypto = { path = "../../core-primitives/sgx/crypto", default-features = false }
itp-stf-state-handler = { path = "../../core-primitives/stf-state-handler", default-features = false }
itp-test = { path = "../../core-primitives/test", default-features = false, optional = true }
itp-types = { path = "../../core-primitives/types", default-features = false }
its-top-pool = { path = "../top-pool", default-features = false }

# sgx enabled external libraries
jsonrpc-core_sgx = { package = "jsonrpc-core", git = "https://github.com/scs/jsonrpc", branch = "no_std", default-features = false, optional = true }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# std compatible external libraries (make sure these versions match with the sgx-enabled ones above)
jsonrpc-core = { version = "18", optional = true }
thiserror = { version = "1.0", optional = true }

# no-std compatible libraries
codec  = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
derive_more = { version = "0.99.5" }
log = { version = "0.4", default-features = false }
sp-core = { version = "5.0.0", default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-runtime = { version = "5.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master"}
