[package]
name = "its-consensus-slots"
version = "0.9.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"


[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
derive_more = "0.99.16"
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
log = { version = "0.4", default-features = false }

# local deps
itp-types = { path = "../../../core-primitives/types", default-features = false }
its-block-verification = { path = "../../block-verification", default-features = false }
its-primitives = { path = "../../primitives", default-features = false }

# only for slot-stream
futures = { version = "0.3", optional = true }
futures-timer = { version = "3.0", optional = true }

# sgx deps
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true, features = ["untrusted_time"] }

# substrate deps
sp-consensus-slots = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

# local deps
itp-settings = { path = "../../../core-primitives/settings" }
itp-sgx-io = { path = "../../../core-primitives/sgx/io", default-features = false }
itp-time-utils = { path = "../../../core-primitives/time-utils", default-features = false }
its-consensus-common = { path = "../common", default-features = false }

[dev-dependencies]
itc-parentchain-test = { path = "../../../core/parentchain/test" }
its-test = { path = "../../test" }
sp-keyring = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
tokio = { version = "1.6.1", features = ["full"] }


[features]
default = ["std"]
std = [
    "codec/std",
    "log/std",
    # only for slot-stream
    "futures",
    "futures-timer",
    # substrate
    "sp-consensus-slots/std",
    "sp-runtime/std",
    # local
    "itp-sgx-io/std",
    "itp-time-utils/std",
    "itp-types/std",
    "its-primitives/std",
    "its-block-verification/std",
    "its-consensus-common/std",
]
sgx = [
    "itp-sgx-io/sgx",
    "itp-time-utils/sgx",
    "its-consensus-common/sgx",
    "sgx_tstd",
]
