[package]
name = "sgx-externalities"
version = "0.2.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[dependencies]
environmental = { version = "1.0.1", default-features = false}
sgx_tstd      = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["untrusted_fs","net","backtrace"]}
sgx_types     = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git"}
sgx_serialize = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_log       = { version = "0.4", package = "log", git = "https://github.com/mesalock-linux/log-sgx"}

[features]
default = ["std"]
std = []