[package]
name = "SealedKeyEnclave"
version = "1.0.0"
authors = ["Alain Brenzikofer"]

[lib]
name = "sealedkeyenclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { git = "https://github.com/baidu/rust-sgx-sdk"}
sgx_tseal = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tstd = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_rand = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tcrypto = { git = "https://github.com/baidu/rust-sgx-sdk" }
rust-crypto = { git = "https://github.com/baidu/rust-sgx-sdk" }
rust-base58 = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_serialize = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_crypto_helper = { package="sgx_crypto_helper_trusted", git = "https://github.com/baidu/rust-sgx-sdk", default-features = false, features = ["enclave_cargo"] }

[target.'cfg(target_env = "sgx")'.dependencies]
sgx_crypto_helper = { package="sgx_crypto_helper_trusted", git = "https://github.com/baidu/rust-sgx-sdk", default-features = false }

[dependencies]
serde_json = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_serialize_derive = { git = "https://github.com/baidu/rust-sgx-sdk" }
parity-codec = { version = "3.0", default-features = false }
primitive-types = { version = "0.2", default-features = false, features = ["codec"] }
blake2-rfc = { version = "0.2.18", default-features = false}

# !!!!!! no_std trouble https://github.com/w3f/schnorrkel/issues/31
#schnorrkel = { git = "https://github.com/scs/schnorrkel.git", default-features = false, features=["alloc", "u64_backend"] }

#only listed to get no_global_allocator feature in
rstd = { package = "sr-std", git = "https://github.com/brenzi/substrate.git", branch="global-allocator-feature", default-features = false, features=["no_global_allocator"]}
#only listed to get no_panic_handler and no_oom  features in
runtime_io = { package = "sr-io", git = "https://github.com/brenzi/substrate.git", branch="global-allocator-feature", default-features = false, features=["no_panic_handler", "no_oom"]}

primitives = { package = "substrate-primitives", git = "https://github.com/brenzi/substrate.git", branch="global-allocator-feature", default-features = false}
runtime_primitives = { package = "sr-primitives", git = "https://github.com/brenzi/substrate.git", branch="global-allocator-feature", default-features = false}
node_runtime = { package = "substratee-node-runtime", git = "https://github.com/scs/substraTEE-node.git", default-features = false, features=["no_global_allocator"] }
#keyring = { package = "substrate-keyring",git = "https://github.com/brenzi/substrate.git", branch="global-allocator-feature", default-features = false}
#node-primitives = { git = "https://github.com/brenzi/substrate.git", branch="global-allocator-feature" }
