[package]
name = "itp-settings"
version = "0.8.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2018"

[dependencies]


[features]
production = []
sidechain = []
offchain-worker = []
teeracle = []
