[package]
name = "itc-light-client"
version = "0.8.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2018"

[features]
default = ["std"]
std = [
    "codec/std",
    "hash-db/std",
    "num/std",
    "log/std",
    "finality-grandpa/std",
    "thiserror",

    # substrate deps
    "frame-system/std",
    "sp-core/std",
    "sp-application-crypto/std",
    "sp-finality-grandpa/std",
    "sp-runtime/std",
    "sp-trie/std",

    # local deps
    "itp-storage/std",
    "itp-sgx-io/std",
]
sgx = [
    "sgx_tstd",
    "thiserror-sgx",
    "itp-sgx-io/sgx",
    "itp-storage/sgx",
]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive", "chain-error"] }
derive_more = { version = "0.99.5" }
finality-grandpa = { version = "0.14.3", default-features = false, features = ["derive-codec"] }
hash-db = { version = "0.15.2", default-features = false }
log = { version = "0.4.14", default-features = false }
num = { package = "num-traits", version = "0.2", default-features = false }
thiserror = { version = "1.0.26", optional = true }

# sgx-deps
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["untrusted_fs"], optional = true}
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
thiserror-sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# local deps
itp-sgx-io = { path = "../../primitives/sgx/io", default-features = false }
itp-settings = { path = "../../primitives/settings", default-features = false }
itp-storage = { path = "../../primitives/storage", default-features = false }

# substrate deps
frame-system = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-core = { version = "4.0.0-dev", default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-application-crypto = { version = "4.0.0-dev", default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-finality-grandpa = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-runtime = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-trie = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master" }