[package]
name = "itp-registry-storage"
version = "0.8.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2018"

[dependencies]
codec = { version = "3.0.0", default-features = false, features = ["derive"], package = "parity-scale-codec" }
sp-std = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20"}

#local deps
itp-storage = { path = "../storage", default-features = false }
itp-types = { path = "../types", default-features = false }

# node deps
pallet-ajuna-gameregistry = { default-features = false, git = "https://github.com/ajuna-network/Ajuna", rev = "polkadot-v0.9.20" }

[features]
default = ["std"]
std = [
    "sp-std/std",
    "itp-storage/std",
    "pallet-ajuna-gameregistry/std",
]
