[package]
name = "itc-rpc-client"
version = "0.8.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2018"

[dependencies]
# crates.io
codec = { package = "parity-scale-codec", version = "2.0.0", features = ["derive"] }
log = "0.4"
openssl = { version = "0.10" }
serde_derive = "1.0"
serde_json = "1.0"
sgx_crypto_helper = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
thiserror = { version = "1.0" }
url = { version = "2.0.0" }
ws = { version = "0.9.1", features = ["ssl"] }
substrate-api-client = { default-features = false, git = "https://github.com/scs/substrate-api-client", branch = "master" }

# local
itp-types = { path = "../../core-primitives/types" }
