[package]
name = "substratee-enclave-api"
version = "0.8.0"
authors = ["clangenbacher <christian.langenbacher@scs.ch>"]
edition = "2018"

[dependencies]
thiserror = "1.0.25"
codec = { package = "parity-scale-codec", version = "2.0.0", features = ["derive"] }

sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }

frame-support = { version = "3.0.0", git = "https://github.com/paritytech/substrate.git", branch = "master" }