[package]
name = "itp-ocall-api"
version = "0.8.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2018"
resolver = "2"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }

# substrate deps
sp-std = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master"}

# sgx-deps
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }

# local deps
itp-types = { path = "../types", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "itp-types/std",
]
