[package]
name = "chain-relay"
version = "0.8.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[features]
default = ["std"]
std = [
    "codec/std",
    "hash-db/std",
    "num/std",
    "log/std",
    "finality-grandpa/std",
    "frame-system/std",
    "sp-core/std",
    "sp-application-crypto/std",
    "sp-finality-grandpa/std",
    "sp-runtime/std",
    "sp-trie/std",
    "substratee-storage/std",
    "substratee-sgx-io/std",
]
sgx = [
    "sgx_tstd",
    "sgx_types",
    "substratee-sgx-io/sgx",
    "substratee-sgx-io/sgx",
]

[dependencies]
derive_more = { version = "0.99.5" }
hash-db = { version = "0.15.2", default-features = false }
log = { version = "0.4.14", default-features = false }
num = { package = "num-traits", version = "0.2", default-features = false }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
finality-grandpa = { version = "0.14.3", default-features = false, features = ["derive-codec"] }

# sgx-deps
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["untrusted_fs"], optional = true}
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

# local deps
substratee-sgx-io = { path = "../../primitives/sgx/io", default-features = false }
substratee-storage = { path = "../../primitives/storage", default-features = false }

# substrate deps
frame-system = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-core = { version = "4.0.0-dev", default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-application-crypto = { version = "4.0.0-dev", default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-finality-grandpa = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-runtime = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-trie = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master" }