[package]
name = "itc-rpc-server"
version = "0.9.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"

[dependencies]
anyhow = "1.0.40"
jsonrpsee = { version = "0.2.0-alpha.7", features = ["full"] }
log = "0.4"
parity-scale-codec = "3.0.0"
serde_json = "1.0.64"
tokio = { version = "1.6.1", features = ["full"] }

# local
itp-enclave-api = { path = "../../core-primitives/enclave-api" }
itp-rpc = { path = "../../core-primitives/rpc" }
itp-utils = { path = "../../core-primitives/utils" }
its-peer-fetch = { path = "../../sidechain/peer-fetch" }
its-primitives = { path = "../../sidechain/primitives" }
its-rpc-handler = { path = "../../sidechain/rpc-handler" }
its-storage = { path = "../../sidechain/storage" }

[features]
default = ["std"]
std = []

[dev-dependencies]
env_logger = { version = "*" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
its-test = { path = "../../sidechain/test" }
