[package]
name = "itp-stf-state-handler"
version = "0.8.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = [
    "rust-base58",
    "ita-stf/std",
    "itp-sgx-crypto/std",
    "itp-sgx-io/std",
    "itp-time-utils/std",
    "itp-types/std",
    "sgx-externalities/std",
    "thiserror",
]
sgx = [
    "sgx_tstd",
    "sgx_tcrypto",
    "rust-base58_sgx",
    "ita-stf/sgx",
    "itp-sgx-crypto/sgx",
    "itp-sgx-io/sgx",
    "itp-time-utils/sgx",
    "sgx-externalities/sgx",
    "thiserror_sgx",
]
test = [
    "itp-sgx-crypto/mocks"
]

[dependencies]
# sgx dependencies
sgx_types = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_tcrypto = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
# local dependencies
ita-stf = { path = "../../app-libs/stf", default-features = false }
itp-settings = { path = "../../core-primitives/settings" }
itp-sgx-crypto = { path = "../../core-primitives/sgx/crypto", default-features = false }
itp-sgx-io = { path = "../../core-primitives/sgx/io", default-features = false }
itp-time-utils = { path = "../../core-primitives/time-utils", default-features = false }
itp-types = { path = "../../core-primitives/types", default-features = false }

# sgx enabled external libraries
rust-base58_sgx = { package = "rust-base58", rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/rust-base58-sgx", optional = true, default-features = false, features = ["mesalock_sgx"] }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# std compatible external libraries (make sure these versions match with the sgx-enabled ones above)
rust-base58 = { package = "rust-base58", version = "0.0.4", optional = true }
thiserror = { version = "1.0", optional = true }

# scs / integritee
sgx-externalities = { default-features = false, git = "https://github.com/integritee-network/sgx-runtime", branch = "master", optional = true }

# no-std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4", default-features = false }
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
sp-core = { version = "6.0.0", default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.20" }

[dev-dependencies]
itp-sgx-crypto = { path = "../../core-primitives/sgx/crypto", features = ["mocks"] }