[package]
name = "itp-stf-state-handler"
version = "0.9.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"

[dependencies]
# sgx dependencies
sgx_tcrypto = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_types = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git" }

# local dependencies
ita-stf = { path = "../../app-libs/stf", default-features = false }
itp-hashing = { path = "../../core-primitives/hashing", default-features = false }
itp-settings = { path = "../../core-primitives/settings" }
itp-sgx-crypto = { path = "../../core-primitives/sgx/crypto", default-features = false }
itp-sgx-externalities = { default-features = false, path = "../../core-primitives/substrate-sgx/externalities" }
itp-sgx-io = { path = "../../core-primitives/sgx/io", default-features = false }
itp-stf-interface = { default-features = false, path = "../../core-primitives/stf-interface" }
itp-stf-state-observer = { path = "../stf-state-observer", default-features = false }
itp-time-utils = { path = "../../core-primitives/time-utils", default-features = false }
itp-types = { path = "../types", default-features = false }

# for tests
itp-sgx-temp-dir = { version = "0.1", default-features = false, optional = true, path = "../../core-primitives/sgx/temp-dir" }

# sgx enabled external libraries
rust-base58_sgx = { package = "rust-base58", rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/rust-base58-sgx", optional = true, default-features = false, features = ["mesalock_sgx"] }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# std compatible external libraries (make sure these versions match with the sgx-enabled ones above)
rust-base58 = { package = "rust-base58", version = "0.0.4", optional = true }
thiserror = { version = "1.0", optional = true }

# no-std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
log = { version = "0.4", default-features = false }
sp-core = { default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }

[dev-dependencies]
itp-sgx-crypto = { path = "../../core-primitives/sgx/crypto", features = ["mocks"] }
itp-stf-state-observer = { path = "../stf-state-observer", features = ["mocks"] }
itp-hashing = { path = "../../core-primitives/hashing", features = ["std"] }

[features]
default = ["std"]
std = [
    "rust-base58",
    "ita-stf/std",
    "itp-sgx-crypto/std",
    "itp-sgx-externalities/std",
    "itp-sgx-io/std",
    "itp-stf-interface/std",
    "itp-stf-state-observer/std",
    "itp-time-utils/std",
    "itp-types/std",
    "thiserror",
    "log/std",
]
sgx = [
    "sgx_tstd",
    "sgx_tcrypto",
    "rust-base58_sgx",
    "ita-stf/sgx",
    "itp-sgx-crypto/sgx",
    "itp-sgx-externalities/sgx",
    "itp-sgx-io/sgx",
    "itp-stf-state-observer/sgx",
    "itp-time-utils/sgx",
    "thiserror_sgx",
]
test = [
    "itp-sgx-crypto/mocks",
    "itp-stf-interface/mocks",
    "itp-sgx-temp-dir",
]
