[package]
name = "sp-io"
version = "2.0.0-alpha.6"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false }
hash-db = { version = "0.15.2", default-features = false }
libsecp256k1 = { version = "0.3.0", optional = true }
log = { version = "0.4.8", optional = true }

environmental = { version = "1.0.1", default-features = false, optional = true }
sgx_tstd      = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["untrusted_fs","net","backtrace"], optional = true}
sgx_types     = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true}
sgx_log       = { version = "0.4", package = "log", git = "https://github.com/mesalock-linux/log-sgx", optional =true }

[dependencies.sp-std]
version = '2.0.0-alpha.6'
default-features = false

[dependencies.sp-core]
version = '2.0.0-alpha.6'
default-features = false

[dependencies.sp-state-machine]
version = '0.8.0-alpha.6'
optional = true

[dependencies.sp-runtime-interface]
version = '2.0.0-alpha.6'
default-features = false

[dependencies.sp-wasm-interface]
version = "2.0.0-alpha.6"
default-features = false

[dependencies.sp-trie]
version = '2.0.0-alpha.6'
optional = true

[dependencies.sp-externalities]
version = '0.8.0-alpha.6'
optional = true

[dependencies.sgx-externalities]
path = "../externalities"
optional = true

[features]
default = ["std"]
std = [
	"sp-core/std",
	"codec/std",
	"sp-std/std",
	"hash-db/std",
	"sp-trie",
	"sp-state-machine",
	"libsecp256k1",
	"sp-runtime-interface/std",
	"sp-externalities",
	"sp-wasm-interface/std",
	"log",
]

sgx = [
	"sgx_tstd",
	"sgx_types",
	"sgx_log",
	"sgx-externalities",
	"environmental",
	"sp-runtime-interface/disable_target_static_assertions",
	"sp-core/full_crypto",
]

# These two features are used for `no_std` builds for the environments which already provides
# `#[panic_handler]`, `#[alloc_error_handler]` and `#[global_allocator]`.
#
# For the regular wasm runtime builds those are not used.
disable_panic_handler = []
disable_oom = []
disable_allocator = []
