[package]
name = "substratee_worker"
version = "4.0.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
build = "build.rs"
edition = "2018"

[dependencies]
ws 						= "0.7"
hex 					= "0.3"
log 					= "0.4"
env_logger 				= "0.6"
rust-base58 			= "0.0.4"
rust-crypto 			= "0.2"
clap 					= { version = "2.33", features = [ "yaml" ] }

dirs 					= "1.0.2"
serde 					= "1.0"
serde_json 				= "1.0"
serde_derive 			= "1.0"

# ipfs
ipfs-api				= "0.5.0-alpha2"
futures 				= "0.1"
hyper 					= "0.12"
multihash 				= "0.8"
cid 					= "0.3"
sha2 					= { version = "0.7", default-features = false }

codec           		= { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
primitive-types    		= { version = "0.6", default-features = false, features = ["codec"] }

sgx_urts				= { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_types 				= { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tseal				= { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_ucrypto 			= { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_crypto_helper 		= { rev = "v1.1.0", git = "https://github.com/apache/teaclave-sgx-sdk.git", default-features = false}

[dependencies.substrate-api-client]
git = "https://github.com/scs/substrate-api-client"
tag = "api-M1.5"

[dependencies.substratee-node-calls]
path = "../substratee-node-calls"

[dependencies.substratee_worker_api]
path = "worker-api"

[dependencies.my_node_runtime]
git = "https://github.com/scs/substraTEE-node"
#rev = "c2309a2f6b140ad914ea809a0348c9432c6c7d30"
branch = "brenzi-sharding"
package = "substratee-node-runtime"

[dependencies.runtime_primitives]
git = "https://github.com/paritytech/substrate"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "sr-primitives"

[dependencies.balances]
git = "https://github.com/paritytech/substrate"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "pallet-balances"

[dependencies.node-primitives]
git = "https://github.com/paritytech/substrate"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"

[dependencies.primitives]
git = "https://github.com/paritytech/substrate"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "substrate-primitives"

[dependencies.keyring]
git = "https://github.com/paritytech/substrate"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "substrate-keyring"

[dependencies.system]
git = "https://github.com/paritytech/substrate"
rev = "3bf9540e72df5ecb3955845764dfee7dcdbb26b5"
package = "palette-system"

[dependencies.substratee-stf]
path = "../stf"
default-features = false

[features]
default = []
production = []
