[package]
name = "itp-storage-verifier"
version = "0.8.0"
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
derive_more = { version = "0.99.5" }

# sgx deps
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }

# substrate deps
sp-core = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master"}
sp-runtime = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master"}
sp-std = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "master"}

# local deps
itp-storage = { path = "../storage", default-features = false }
itp-ocall-api = { path = "../ocall-api", default-features = false }
itp-core = { path = "../core", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    "itp-storage/std",
    "itp-ocall-api/std",
    "itp-core/std",
]