[package]
name = "itc-direct-rpc-server"
version = "0.8.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
sgx = [
    "sgx_tstd",
    "sgx_types",
    "jsonrpc-core_sgx",
    "thiserror_sgx",
    "itc-tls-websocket-server/sgx",
]
std = [
    "jsonrpc-core",
    "itp-types/std",
    "thiserror",
    "itc-tls-websocket-server/std",
]

[dependencies]
# sgx dependencies
sgx_types   = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_tstd    = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true, features = ["net", "thread"] }

# no-std dependencies
codec  = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4", default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
sp-runtime = { version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.19" }

# internal dependencies
itp-types = { path = "../../core-primitives/types", default-features = false }
itc-tls-websocket-server = { path = "../tls-websocket-server", default-features = false }

# sgx enabled external libraries
jsonrpc-core_sgx = { package = "jsonrpc-core", git = "https://github.com/scs/jsonrpc", branch = "no_std", default-features = false, optional = true }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# std compatible external libraries (make sure these versions match with the sgx-enabled ones above)
jsonrpc-core = { version = "18", optional = true }
thiserror = { version = "1.0", optional = true }
