[package]
name = "itc-direct-rpc-server"
version = "0.9.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"

[dependencies]
# sgx dependencies
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true, features = ["net", "thread"] }
sgx_types = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

# no-std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4", default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

# local
itc-tls-websocket-server = { path = "../tls-websocket-server", default-features = false }
itp-rpc = { path = "../../core-primitives/rpc", default-features = false }
itp-types = { default-features = false, path = "../../core-primitives/types" }
itp-utils = { default-features = false, path = "../../core-primitives/utils" }

# sgx enabled external libraries
jsonrpc-core_sgx = { package = "jsonrpc-core", git = "https://github.com/scs/jsonrpc", branch = "no_std_v18", default-features = false, optional = true }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# std compatible external libraries (make sure these versions match with the sgx-enabled ones above)
jsonrpc-core = { version = "18", optional = true }
thiserror = { version = "1.0", optional = true }

[features]
default = ["std"]
std = [
    # no-std dependencies
    "codec/std",
    "log/std",
    "serde_json/std",
    "sp-runtime/std",
    # integritee dependencies
    "itp-types/std",
    "itp-utils/std",
    # local
    "itc-tls-websocket-server/std",
    "itp-rpc/std",
    # optional ones
    "jsonrpc-core",
    "thiserror",
]
sgx = [
    "itc-tls-websocket-server/sgx",
    "itp-rpc/sgx",
    "itp-utils/sgx",
    "jsonrpc-core_sgx",
    "sgx_tstd",
    "sgx_types",
    "thiserror_sgx",
]
mocks = []
